### ISSUE TITLE
Add support for groups?

### ISSUE THREAD

**Issue by tehviking** [xavier/huex#1]
First off, thanks for the awesome project, I was doing manual API calls in my Slack bot project but I'm now rewriting it to use this instead, it's really well written from what I can tell, and was easy to extend.

I created a fork that adds support for fetching and changing stuff for groups in the grossest and jankiest way possible.

It's my first elixir project so it's not something I'd issue a pull request for, but if you have any thoughts or pointers as to how to re-architect, I'm open to suggestions.

https://github.com/tehviking/huex

Thanks!

**Comment by xavier** [comment]
Thanks for the feedback, I just came back from holidays and I'll have a look at it asap!

**Comment by xavier** [comment]
Your code is fine and has been merged. Thanks! :+1: 

I may do some refactoring later to extract a few redundant payload building code but it's definitely Good Enough for a release. The new hex package has been published, feel free to upgrade your dependencies.
