### ISSUE TITLE
Possibly out of date with Philips Hue API

### ISSUE THREAD

**Issue by bruce** [xavier/huex#3]
It appears that the package is using a slightly older version of the Philips Hue API, that's no longer supported.

Authorization isn't done with a separate `username` param now, according to the API docs:

``` elixir
iex(1)> bridge = Huex.connect("192.168.0.20") |> Huex.authorize("huetest")
%Huex.Bridge{error: [%{"error" => %{"address" => "/username",
      "description" => "parameter, username, not available", "type" => 6}}],
 host: "192.168.0.20", status: :error, username: "huetest"}
```

 I was able to make it work with the following change:

``` diff
-  @spec authorize(Bridge.t, binary) :: Bridge.t
-  def authorize(bridge, username) do
-    payload = %{devicetype: "test user", username: username}
+  @spec authorize(Bridge.t, String.t, String.t, String.t) :: Bridge.t
+  def authorize(bridge, application_name, device_type, username) do
+    payload = %{devicetype: application_name <> "#" <> device_type <> " " <> username}
     bridge = bridge |> api_url |> post_json(payload) |> update_bridge(bridge)
     %Bridge{bridge | username: username}
   end
```

Example:

``` elixir
iex(3)> bridge = Huex.connect("192.168.0.20") |> Huex.authorize("huetest", "elixir", "huetest")
%Huex.Bridge{error: [%{"error" => %{"address" => "",
      "description" => "link button not pressed", "type" => 101}}],
 host: "192.168.0.20", status: :error, username: "huetest"}
iex(4)> bridge = Huex.connect("192.168.0.20") |> Huex.authorize("huetest", "elixir", "huetest")
%Huex.Bridge{error: nil, host: "192.168.0.20", status: :ok, username: "huetest"}
```

This doesn't appear to be the end of the API mismatch problems, however:

``` elixir
iex(5)> Huex.info(bridge)
[%{"error" => %{"address" => "/", "description" => "unauthorized user",
     "type" => 1}}]
iex(6)> bridge
%Huex.Bridge{error: nil, host: "192.168.0.20", status: :ok, username: "huetest"}
iex(7)> Huex.lights(bridge)
[%{"error" => %{"address" => "/lights", "description" => "unauthorized user",
     "type" => 1}}]
```

As I have a pretty extensive Philips Hue setup in my house and am excited about automating it, I'm happy to assist, but I wasn't sure what the plans with the package may be. Please let me know.

**Comment by mrbriandavis** [comment]
@bruce - I quickly looked at this issue and tried this https://github.com/xavier/huex/pull/4 this seemed to make this work for me. The pull request explains the Hue API change that likely broke this implementation.

**Comment by xavier** [comment]
@bruce I'm very sorry for coming back to you so late, I somehow missed the notification about this issue and it was only brought to my attention by @mrbriandavis pull request. The issue is being addressed and a new version of the package will be available shortly.

**Comment by xavier** [comment]
Huex 0.6.0 has been published to hex, it includes support for the new authorization API.
