### ISSUE TITLE
No process while attempting to run examples

### ISSUE THREAD

**Issue by jphastings** [xavier/huex#7]
Forgive my lack of experience with Elixir; I'm having a hard time getting the examples working in IEx. Am I missing some kind of initialisation step?

Many thanks!

(I'm attempting to connect to [this Hue Emulator](http://steveyo.github.io/Hue-Emulator/), hence the port number in the first argument, but as you can see, Huex is failing before it opens any connections) 

```
iex(1)> bridge = Huex.connect("127.0.0.1:8000") |> Huex.authorize("my_app#my_device")
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.283.0>, #Reference<0.0.1.971>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_tcp, '127.0.0.1', 4001, "127.0.0.1:4001", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
             deps/hackney/src/hackney_manager.erl:66: :hackney_manager.init_request/1
             deps/hackney/src/hackney_manager.erl:56: :hackney_manager.new_request/1
             deps/hackney/src/hackney_connect.erl:185: :hackney_connect.socket_from_pool/4
             deps/hackney/src/hackney_connect.erl:37: :hackney_connect.connect/5
             deps/hackney/src/hackney.erl:328: :hackney.request/5
             lib/httpoison/base.ex:402: HTTPoison.Base.request/9
             lib/huex.ex:381: Huex.post_json/2
```

**Comment by xavier** [comment]
It looks like the `HTTPoison` server is not started, which is weird since it should be automatically started as it's declared as a runtime dependency of the library.

Could you try `HTTPoison.get("http://google.com")` in the same iex session?
If you run into the same error, execute `HTTPoison.start()` and retry.

**Comment by jphastings** [comment]
Running `HTTPoison.start()` fixed both calls! It seems the HTTPoison server isn't starting - I'll manually start it for the meanwhile, but do let me know if there's anything I can do to help the debugging!
